# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Networking' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Networking

pod 'SVProgressHUD'
pod 'Alamofire', '~> 5.0.0-beta.2'






end
